apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ens-dynamic
spec:
  storageClassName: "expense-ebs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1f
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-dynamic
      persistentVolumeClaim:
        claimName: ebs-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007